services:
  # Web Service for FastAPI Backend
  - type: web
    name: foresight-analyzer-api
    runtime: python
    region: oregon # oregon, frankfurt, ohio, singapore
    plan: free # Free tier!
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENROUTER_API_KEY
        value: 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
      - key: OPENROUTER_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: ENABLED_MODELS
        value: x-ai/grok-4-fast:free,google/gemini-2.0-flash-exp:free,qwen/qwen-2.5-72b-instruct:free
      - key: ITERATIONS_PER_MODEL
        value: "5"
      - key: CONCURRENT_REQUESTS
        value: "1"
      - key: REQUEST_TIMEOUT
        value: "120"
      - key: RATE_LIMIT_DELAY
        value: "10"
      - key: MAX_RETRIES_FREE
        value: "5"
      - key: BACKOFF_MULTIPLIER
        value: "2"
    # Health check endpoint to keep service alive
    healthCheckPath: /health
    autoDeploy: true # Auto deploy on git push