services:
  # Web Service for FastAPI Backend
  - type: web
    name: foresight-analyzer-api
    runtime: python
    region: oregon # oregon, frankfurt, ohio, singapore
    plan: free # Free tier!
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENROUTER_API_KEY
        value: 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
      - key: OPENROUTER_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: ENABLED_MODELS
        value: x-ai/grok-4-fast:free,deepseek/deepseek-r1-distill-llama-70b:free,qwen/qwen-2.5-72b-instruct:free,qwen/qwen-2-vl-72b-instruct:free,google/gemini-2.0-flash-exp:free,google/gemma-2-9b-it:free,mistralai/mistral-7b-instruct:free,meta-llama/llama-3.2-3b-instruct:free
      - key: ITERATIONS_PER_MODEL
        value: "5"
      - key: CONCURRENT_REQUESTS
        value: "1"
      - key: REQUEST_TIMEOUT
        value: "120"
      - key: RATE_LIMIT_DELAY
        value: "5"
    # Health check endpoint to keep service alive
    healthCheckPath: /health
    autoDeploy: true # Auto deploy on git push